source "https://rubygems.org"

ruby "3.3.2"

gem "rails", "~> 7.1.3"
gem "pg", ">= 1.1"
gem "puma", "~> 6.4"

gem "faraday", "~> 2.9"         # HTTP client
gem "bunny", "~> 2.22"          # RabbitMQ client

gem "dotenv-rails", groups: [:development, :test]

gem "bootsnap", require: false

gem 'rswag-api'
gem 'rswag-ui'

gem 'active_model_serializers', '~> 0.10.13'

gem 'kaminari'

group :development, :test do
  gem "rspec-rails", "~> 6.1.1"
  gem "factory_bot_rails"
  gem "faker"
  gem "pry"
  gem 'rswag-specs'
  gem 'byebug'
end


group :test do
  gem "webmock"
  gem "database_cleaner-active_record"
  gem 'simplecov', require: false
  gem 'shoulda-matchers', '~> 5.3'
end

group :development do
  gem "listen"
  gem "spring"
  gem "spring-watcher-listen"
end
