default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV["DB_HOST"] || "localhost" %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: <%= ENV["DB_NAME"] %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV["DB_NAME_TEST"] || "#{ENV["DB_NAME"]}_test" %>

production:
  <<: *default